### ISSUE TITLE
Features I cannot find

### ISSUE THREAD

**Issue by MIKE-DAILEY** [FrSky-OS/discussion#10]
Cannot find where expo is set unless it is part of DR or Pit Curve.

Cannot find sequencer

Cannot find instant trim setting.

Cannot find control for flight data logging

Most flyers use flight modes and I see it in helicopter but not fixed wing.

Do not see controls for the 3-axis gyro and 3-axis accelerator

Do not see control for GPS module

Mike

**Comment by AloftHobbies** [comment]
We should open a new issue for each of these points. The expo and trim settings have already been started.

**Comment by MIKE-DAILEY** [comment]
Added new issue for each point not covered yet.
