### ISSUE TITLE
In the main Model menu the button "SERVO" should be renamed "MONITOR"

### ISSUE THREAD

**Issue by prondel** [FrSky-OS/discussion#18]
In the main Model menu the button "SERVO" is misleading and should be renamed "MONITOR" 

![image](https://cloud.githubusercontent.com/assets/16406160/11965909/532d2cc0-a8f8-11e5-82f6-c21140148078.png)

**Comment by AloftHobbies** [comment]
Agreed.

**Comment by janekx** [comment]
GUI 1230 have it fixed
