### ISSUE TITLE
[General Comment] No flight conditions !!!

### ISSUE THREAD

**Issue by prondel** [FrSky-OS/discussion#25]
I haven't seen any place in the menu to configure flight conditions. This is a critical missing feature.

**Comment by janekx** [comment]
In Custom model type it is present. Try to create model in custom

**Comment by prondel** [comment]
OK, but Custom model doesn't have the pre-defined mixers :(

**Comment by MIKE-DAILEY** [comment]
The model type seems to control witch features are available.  There is a “Condition” menu in helicopter.  Not sure is that is a flight condition.   I wonder how you add features to a model type?

**Comment by janekx** [comment]
This is good for discusion if we need conditions everywhere.  Not everywhere is f modes needed.  If i look at airplane mode it is very easy template where can lack of fmodes

**Comment by AloftHobbies** [comment]
Glider has flight modes and predefined mixes. Each mix has a pull down for the different flight modes.

**Comment by prondel** [comment]
ok, my mistake. They are predefined and limited to 5. 
This will be enough for 95% of the pilot.

**Comment by janekx** [comment]
System is tamplate based and custom as well so this is not issue.
