### ISSUE TITLE
Selection dial issue

### ISSUE THREAD

**Issue by jaweber1** [FrSky-OS/discussion#37]
I'm not sure what to call it, but the selection dial is inconsistent.  I've found the best way to use it is to move the mouse in a circle around it like you would with your finger, but it's sensitivity is inconsistent.  Sometimes it moves one selection at a time evenly and other times it seems to skip selection items.  This seems most prevalent on the main menu screens.

Also, there are times when it skips around the selections in an order that is not expected.  It should always move down and then right for clockwise and up and then left for counter clockwise.  When I find examples, I'll post follow up comments to this issue.

**Comment by jaweber1** [comment]
I just found a place where it is mostly inconsistent.  On the system menu trying to select Sound, it will often skip over the Sound menu and go straight from Display to Music.

**Comment by MIKE-DAILEY** [comment]
I've noticed that too.

**Comment by janekx** [comment]
Yes please not waste time with simu control issues,  it will be issue when it will be on real Horus radio hw and not in PC.  Our goal is to hunt issues from menu and so.  Thanks for understand :)

**Comment by AloftHobbies** [comment]
While this is super annoying in the simulator, it should not be an issue on the radio. We will need to wait until we have hardware to test, but pretty sure this is just limited to the simulator. I'm going to close this issue for now.
