### ISSUE TITLE
Dual rates 

### ISSUE THREAD

**Issue by MIKE-DAILEY** [FrSky-OS/discussion#6]
Dual rates - I prefer to be able to use triple rates on a three position switch.  The simulator looks like the dual rates have more than two but not sure how to make it work.   Dual rates seem to be changing the servo movement curve or expo not the percentage of movement in each direction.   Usually I would have rate 1 (100%) rate 2 (80%) and rate 3 (60%) servo movements on the three position switch.  Anyone figure out how to set the rates?

Mike

**Comment by AloftHobbies** [comment]
Closing this thread as issue 19 has it covered in more detail.
https://github.com/FrSky-OS/discussion/issues/19
