### ISSUE TITLE
Complex mixing options.

### ISSUE THREAD

**Issue by Poffertjesporem** [FrSky-OS/discussion#64]
I don't know if the hardware is ready for this, but I would love to be able to mix an airspeed sensor to the control surface deflection (high speed, small deflection-slow speed, large deflection). Changing expo at the same time, to keep the center of the sticks feel constant. 

The TX software needs to be (IMO) able to accept 3th party hardware(sensors ect).

**Comment by AloftHobbies** [comment]
I think this would be a feature of the logic switches being discussed on another thread.

**Comment by Poffertjesporem** [comment]
I agree.
