### ISSUE TITLE
Simu 1.1  one year old now, no updates

### ISSUE THREAD

**Issue by hrenz** [FrSky-OS/discussion#73]
Simu1.1 one year old, no updates availabel

This kind of FrSky-OS for Horus it only embarrassing and disappointing!

there is nothing more to say

**Comment by janekx** [comment]
I am not sure what version you use but simu from 05/15 was absolutely other than simu we have now. We use simu that is about 2 month old and we discus it here https://github.com/FrSky-OS/discussion/issues/67
