### ISSUE TITLE
GUI 1230 Layout of the Simu

### ISSUE THREAD

**Issue by Woita2095** [FrSky-OS/discussion#81]
New Layout of the Simu looks better then previous. But there are some new bugs, especially the Sticks J1, J2, J3, J4 are scrambled (vertically x horizontally).
![direction of the sticks](https://cloud.githubusercontent.com/assets/16479304/12054175/1eea204c-af21-11e5-8aaf-942c61f93856.jpg)

It would by nice, if the Layout in the Simu was exactly the same as in real transmitter. Including switches, sliders and so on.

... And one more question: Why the Simu is divided into two windows (the Main Window and the Control pad)?
I think Simu could be only one window, like real transmitter.

**Comment by janekx** [comment]
Cerrected in V1 redownload GUI 1230_1

**Comment by Woita2095** [comment]
I acknowledge, promptly fixed.
